[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/callback"
  status = 200

[[redirects]]
  from = "/api/import"
  to = "/.netlify/functions/import-product"
  status = 200

[dev]
  functions = "netlify/functions"
