[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/callback"
  status = 200

[[redirects]]
  from = "/api/import"
  to = "/.netlify/functions/import-product"
  status = 200

[[redirects]]
  from = "/api/billing"
  to = "/.netlify/functions/billing"
  status = 200

[[redirects]]
  from = "/api/usage"
  to = "/.netlify/functions/usage"
  status = 200

[[redirects]]
  from = "/auth/google/callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/check-phone"
  to = "/.netlify/functions/check-phone"
  status = 200
  