# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c73e2a3da0ece8fbdd7ecfb9e8ba489"
name = "Importr"
application_url = "https://importr.io"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://importr.io" ]